env:
  es6: true
  node: true
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 8
rules:
  no-unused-vars:
    - warn
  no-undef:
    - error
  indent:
    - warn
    - 2
  semi:
    - error
    - always
  prefer-const:
    - warn
