
variables:
  PROJECT_NAME: curatrix
  CHART_PATH: deploy/$PROJECT_NAME
  AMD64_IMAGE_TAG: :$CI_COMMIT_REF_NAME
  AMD64_TEST_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  ARMv6_IMAGE_TAG: $CI_REGISTRY_IMAGE/arm32v6:$CI_COMMIT_REF_NAME
  # GCLOUD_PROJECT: katchecode-shared-hosting
  CHART_REPO: charts.katchecode.com/$PROJECT_NAME
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

docker_build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - for IMAGES in images/*/
    - do
    -   IMAGE_TAG=$CI_REGISTRY_IMAGE/$(basename $IMAGES)
    -   docker build -t $IMAGE_TAG $D -f "$IMAGES"build/Dockerfile
    -   docker push $IMAGE_TAG
    - done


# arm32v6:
#   stage: build
#   image: docker
#   allow_failure: true
#   tags:
#     - docker
#     - arm32
#   services:
#     - docker:dind
#   script:
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#     - docker build -t $ARMv6_IMAGE_TAG -f build/Dockerfile-arm32v6 .
#     - docker push $ARMv6_IMAGE_TAG

helm_tests:
  stage: test
  image: $
  variables:
    TEST_MONGODB_ENDPOINT: mongodb://mongo/tests
    TEST_TARGET_ENDPOINT: http://target-server
    MONGODB_ENDPOINT: mongodb://mongo/tests
  script:
    - yarn start

lint_chart:
  stage: test
  image: katchecode/gcloud-kubernetes-helm
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - for CHARTS in charts/*/
    - do
    -   helm lint $CHARTS
    - done

lint_service:
  stage: test
  image: node
  script:
    - yarn install
    - yarn lint

# test_chart:
#   stage: test
#   image: mstrzele/minikube:v0.22.2
#   services:
#     - docker:dind
#   script:
#     - minikube start
#     -

deploy_chart:
  stage: deploy
  image: katchecode/gcloud-kubernetes-helm
  script:
  - echo "$GCLOUD_SERVICE_ACCOUNT_KEY" | gcloud auth activate-service-account --key-file=-
  # - gcloud config set project $GCLOUD_PROJECT
  # - helm plugin install https://github.com/nouney/helm-gcs
  # - helm repo add katchecode gs://$BUCKET_PATH
  - mkdir chart_package
  - helm package $CHART_PATH -d chart_package/
  - gsutil cp gs://$CHART_REPO/index.yaml chart_package/ && MERGE_OPTION=--merge chart_package/index.yaml
  - helm repo index chart_package/ --url $CHART_REPO $MERGE_OPTION
  - gsutil cp -n chart_package/* gs://$CHART_REPO/
  - gsutil acl ch -u AllUsers:R gs://$CHART_REPO/*
