
stages:
  - build
  - test
  - deploy

build-server:
  stage: build
  image: golang:1.12.7-alpine
  variables:
    CGO_ENABLED: '0'
    GOOS: linux
    GOARCH: amd64
    GOMAXPROCS: '128'
  artifacts:
    paths:
    - build/deqd
    - build/deqctl
  script:
  - apk add --no-cache git
  - go build -o build/deqd ./cmd/deqd
  - go build -o build/deqctl ./cmd/deqctl

# api-tests:
#   stage: test
#   image: golang:1.10.3-alpine
#   variables:
#     CGO_ENABLED: "0"
#     GOOS: linux
#   services:
#     - docker:dind
#   script:
#     - go test gitlab.com/charterpay/deqd/cmd/deqd_tests

deploy-deqd:
  stage: deploy
  image: docker
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME build/
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

deploy-deqctl:
  stage: deploy
  image: docker
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE/deqctl:$CI_COMMIT_REF_NAME -f build/Dockerfile-deqctl build/
  - docker push $CI_REGISTRY_IMAGE/deqctl:$CI_COMMIT_REF_NAME
