
variables:

  PROJECT_NAME: curatrix
  CHART_REPO: charts.katchecode.com/$PROJECT_NAME
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

build_images:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - |
      for IMAGE in images/*/; do
        IMAGE_TAG=$CI_REGISTRY_IMAGE/$(basename $IMAGE)
        docker build -t $IMAGE_TAG $IMAGE -f "$IMAGE"build/Dockerfile
        docker push $IMAGE_TAG
      done


# arm32v6:
#   stage: build
#   image: docker
#   allow_failure: true
#   tags:
#     - docker
#     - arm32
#   services:
#     - docker:dind
#   script:
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#     - docker build -t $ARMv6_IMAGE_TAG -f build/Dockerfile-arm32v6 .
#     - docker push $ARMv6_IMAGE_TAG

# chart_tests:
#   stage: test
#   image: lachlanevenson/k8s-helm
#   script:
#     - for CHART in charts/*/
#     - do
#     -   helm install $CHART --wait --devel --dep-up
#     -   helm test $CHART
#     - done

lint_chart:
  stage: test
  image: lachlanevenson/k8s-helm
  script:
    - |
      for CHART in charts/*/; do
        helm lint $CHART
      done
#
# lint_image:
#   stage: test
#   image: docker
#   script:
#     - for IMAGE in images/*/
#     - do
#     -   helm lint $IMAGE/build/Dockerfile-lint
#     - done


deploy_chart:
  stage: deploy
  image: katchecode/gcloud-kubernetes-helm
  script:
  - echo "$GCLOUD_SERVICE_ACCOUNT_KEY" | gcloud auth activate-service-account --key-file=-
  - RELEASE_FOLDER=$(mktemp -d)
  - |
    for CHART in charts/*/; do
      helm package $CHART -d $RELEASE_FOLDER
      helm lint $CHART
    done
  - gsutil cp gs://$CHART_REPO/index.yaml $RELEASE_FOLDER/ && MERGE_OPTION=--merge $RELEASE_FOLDER/index.yaml
  - helm repo index $RELEASE_FOLDER/ --url $CHART_REPO $MERGE_OPTION
  - gsutil cp -n $RELEASE_FOLDER/* gs://$CHART_REPO/
  - gsutil acl ch -u AllUsers:R gs://$CHART_REPO/*
