
variables:
  PROJECT_NAME: curatrix
  CHART_REPO_BUCKET: charts.katchecode.com
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

build_images:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - |
      for IMAGE in images/*/; do
        IMAGE_TAG=$CI_REGISTRY_IMAGE/$(basename $IMAGE):$CI_COMMIT_SHA
        docker build -t $IMAGE_TAG $IMAGE -f "$IMAGE"build/Dockerfile
        docker push $IMAGE_TAG
        if [ -n "$CI_COMMIT_TAG" ]; then
          VERSION_TAG=$CI_REGISTRY_IMAGE/$(basename $IMAGE):$CI_COMMIT_TAG
          docker tag $IMAGE_TAG $VERSION_TAG
          docker push $VERSION_TAG
        fi
      done


# arm32v6:
#   stage: build
#   image: docker
#   allow_failure: true
#   tags:
#     - docker
#     - arm32
#   services:
#     - docker:dind
#   script:
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#     - docker build -t $ARMv6_IMAGE_TAG -f build/Dockerfile-arm32v6 .
#     - docker push $ARMv6_IMAGE_TAG

# chart_tests:
#   stage: test
#   image: lachlanevenson/k8s-helm
#   script:
#     - for CHART in charts/*/
#     - do
#     -   helm install $CHART --wait --devel --dep-up
#     -   helm test $CHART
#     - done

lint_chart:
  stage: test
  image: katchecode/gcloud-kubernetes-helm
  script:
    - |
      for CHART in charts/*/; do
        helm lint $CHART
      done


deploy_chart:
  stage: deploy
  image: katchecode/gcloud-kubernetes-helm
  only:
    - tags
    - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
  script:
  - INDEX=0
  - echo "$GCLOUD_SERVICE_ACCOUNT_KEY" | gcloud auth activate-service-account --key-file=-
  - RELEASE_FOLDER=$(mktemp -d)
  - helm repo add kc https://charts.katchecode.com
  - |
    for CHART in charts/*/; do
      helm dep build $CHART
      helm package $CHART -d $RELEASE_FOLDER --app-version ${CI_COMMIT_TAG#v} --version ${CI_COMMIT_TAG#v} --save=false
    done
  - gsutil cp -n $RELEASE_FOLDER/* gs://$CHART_REPO_BUCKET/
  - gsutil acl ch -u AllUsers:R gs://$CHART_REPO_BUCKET/*
