
stages:
  - build
  - test
  - deploy

build-server:
  stage: build
  image: golang:1.11.0-alpine
  variables:
    CGO_ENABLED: "0"
    GOOS: linux
  artifacts:
    paths:
    - build/deqd
  script:
  - apk add --no-cache git
  - go build -o build/deqd ./cmd/deqd

# api-tests:
#   stage: test
#   image: golang:1.10.3-alpine
#   variables:
#     CGO_ENABLED: "0"
#     GOOS: linux
#   services:
#     - docker:dind
#   script:
#     - go test gitlab.com/charterpay/deqd/cmd/deqd_tests

deploy-server:
  stage: deploy
  image: docker
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME build/
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
