
variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

build-server:
  stage: build
  image: golang:1.10.3-alpine
  variables:
    GOPATH: /go
    CGO_ENABLED: "0"
    GOOS: linux
  artifacts:
    paths:
    - build/deqd
  before_script:
  - mkdir -p /go/src/gitlab.com/katcheCode/charter-success
  - ln -s $CI_PROJECT_DIR /go/src/gitlab.com/katcheCode/charter-success/deqd
  - cd /go/src/gitlab.com/katcheCode/charter-success/deqd
  script:
  - apk add --no-cache git
  - go get ./cmd/deqd
  - go build -o build/deqd ./cmd/deqd

# api-tests:
#   stage: test
#   image: golang:1.10.3-alpine
#   variables:
#     CGO_ENABLED: "0"
#     GOOS: linux
#   services:
#     - docker:dind
#   script:
#     - go test gitlab.com/katcheCode/charter-success/deqd/cmd/deqd_tests

deploy-server:
  stage: deploy
  image: docker
  services:
    - docker:dind
  script:
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME build/
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
