// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: data.proto

package data

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type EventState int32

const (
	EventState_UNSPECIFIED_STATE EventState = 0
	EventState_QUEUED            EventState = 1
	EventState_DEQUEUED_OK       EventState = 2
	EventState_DEQUEUED_ERROR    EventState = 3
)

var EventState_name = map[int32]string{
	0: "UNSPECIFIED_STATE",
	1: "QUEUED",
	2: "DEQUEUED_OK",
	3: "DEQUEUED_ERROR",
}

var EventState_value = map[string]int32{
	"UNSPECIFIED_STATE": 0,
	"QUEUED":            1,
	"DEQUEUED_OK":       2,
	"DEQUEUED_ERROR":    3,
}

func (x EventState) String() string {
	return proto.EnumName(EventState_name, int32(x))
}

func (EventState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

type ChannelPayload struct {
	EventState   EventState `protobuf:"varint,1,opt,name=event_state,json=eventState,proto3,enum=EventState" json:"event_state,omitempty"`
	RequeueCount int32      `protobuf:"varint,2,opt,name=requeue_count,json=requeueCount,proto3" json:"requeue_count,omitempty"`
}

func (m *ChannelPayload) Reset()         { *m = ChannelPayload{} }
func (m *ChannelPayload) String() string { return proto.CompactTextString(m) }
func (*ChannelPayload) ProtoMessage()    {}
func (*ChannelPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}
func (m *ChannelPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChannelPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChannelPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChannelPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelPayload.Merge(m, src)
}
func (m *ChannelPayload) XXX_Size() int {
	return m.Size()
}
func (m *ChannelPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelPayload proto.InternalMessageInfo

func (m *ChannelPayload) GetEventState() EventState {
	if m != nil {
		return m.EventState
	}
	return EventState_UNSPECIFIED_STATE
}

func (m *ChannelPayload) GetRequeueCount() int32 {
	if m != nil {
		return m.RequeueCount
	}
	return 0
}

type EventTimePayload struct {
	CreateTime int64 `protobuf:"fixed64,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (m *EventTimePayload) Reset()         { *m = EventTimePayload{} }
func (m *EventTimePayload) String() string { return proto.CompactTextString(m) }
func (*EventTimePayload) ProtoMessage()    {}
func (*EventTimePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}
func (m *EventTimePayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventTimePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventTimePayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventTimePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventTimePayload.Merge(m, src)
}
func (m *EventTimePayload) XXX_Size() int {
	return m.Size()
}
func (m *EventTimePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_EventTimePayload.DiscardUnknown(m)
}

var xxx_messageInfo_EventTimePayload proto.InternalMessageInfo

func (m *EventTimePayload) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type IndexPayload struct {
	EventId    string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	CreateTime int64  `protobuf:"fixed64,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (m *IndexPayload) Reset()         { *m = IndexPayload{} }
func (m *IndexPayload) String() string { return proto.CompactTextString(m) }
func (*IndexPayload) ProtoMessage()    {}
func (*IndexPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}
func (m *IndexPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IndexPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IndexPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IndexPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexPayload.Merge(m, src)
}
func (m *IndexPayload) XXX_Size() int {
	return m.Size()
}
func (m *IndexPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexPayload.DiscardUnknown(m)
}

var xxx_messageInfo_IndexPayload proto.InternalMessageInfo

func (m *IndexPayload) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *IndexPayload) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type EventPayload struct {
	Payload           []byte     `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	DefaultEventState EventState `protobuf:"varint,2,opt,name=default_event_state,json=defaultEventState,proto3,enum=EventState" json:"default_event_state,omitempty"`
	Indexes           []string   `protobuf:"bytes,3,rep,name=indexes,proto3" json:"indexes,omitempty"`
}

func (m *EventPayload) Reset()         { *m = EventPayload{} }
func (m *EventPayload) String() string { return proto.CompactTextString(m) }
func (*EventPayload) ProtoMessage()    {}
func (*EventPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}
func (m *EventPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPayload.Merge(m, src)
}
func (m *EventPayload) XXX_Size() int {
	return m.Size()
}
func (m *EventPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPayload.DiscardUnknown(m)
}

var xxx_messageInfo_EventPayload proto.InternalMessageInfo

func (m *EventPayload) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *EventPayload) GetDefaultEventState() EventState {
	if m != nil {
		return m.DefaultEventState
	}
	return EventState_UNSPECIFIED_STATE
}

func (m *EventPayload) GetIndexes() []string {
	if m != nil {
		return m.Indexes
	}
	return nil
}

func init() {
	proto.RegisterEnum("EventState", EventState_name, EventState_value)
	proto.RegisterType((*ChannelPayload)(nil), "ChannelPayload")
	proto.RegisterType((*EventTimePayload)(nil), "EventTimePayload")
	proto.RegisterType((*IndexPayload)(nil), "IndexPayload")
	proto.RegisterType((*EventPayload)(nil), "EventPayload")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4e, 0xf2, 0x40,
	0x14, 0x85, 0x3b, 0x25, 0x3f, 0xfc, 0xde, 0x56, 0x2c, 0x63, 0x4c, 0xea, 0xa6, 0x12, 0xdc, 0x10,
	0x63, 0x58, 0xc8, 0xd2, 0x95, 0xc2, 0x98, 0x54, 0x13, 0xc1, 0xa1, 0xac, 0x9b, 0x91, 0x5e, 0x63,
	0x13, 0x68, 0x11, 0xa6, 0x46, 0x57, 0xbe, 0x82, 0x8f, 0xe5, 0x92, 0xa5, 0x4b, 0x03, 0x2f, 0x62,
	0x66, 0x4a, 0x91, 0x84, 0xdd, 0x9c, 0x2f, 0xe7, 0x9e, 0x7b, 0x72, 0x07, 0x20, 0x12, 0x52, 0xb4,
	0xa6, 0xb3, 0x54, 0xa6, 0x8d, 0x11, 0x54, 0x3b, 0xcf, 0x22, 0x49, 0x70, 0xdc, 0x17, 0xef, 0xe3,
	0x54, 0x44, 0xf4, 0x1c, 0x2c, 0x7c, 0xc5, 0x44, 0x86, 0x73, 0x29, 0x24, 0xba, 0xa4, 0x4e, 0x9a,
	0xd5, 0x0b, 0xab, 0xc5, 0x14, 0x1b, 0x28, 0xc4, 0x01, 0x37, 0x6f, 0x7a, 0x0a, 0xfb, 0x33, 0x7c,
	0xc9, 0x30, 0xc3, 0x70, 0x94, 0x66, 0x89, 0x74, 0xcd, 0x3a, 0x69, 0xfe, 0xe3, 0xf6, 0x1a, 0x76,
	0x14, 0x6b, 0xb4, 0xc1, 0xd1, 0xe3, 0x41, 0x3c, 0xc1, 0x62, 0xcd, 0x09, 0x58, 0xa3, 0x19, 0x0a,
	0x89, 0xa1, 0x8c, 0x27, 0xf9, 0x1a, 0x87, 0x43, 0x8e, 0x94, 0xaf, 0x71, 0x0b, 0xb6, 0x9f, 0x44,
	0xf8, 0x56, 0x0c, 0x1c, 0xc3, 0xff, 0xbc, 0x57, 0x1c, 0x69, 0xf7, 0x1e, 0xaf, 0x68, 0xed, 0xef,
	0x64, 0x99, 0x3b, 0x59, 0x1f, 0x60, 0xeb, 0x02, 0x45, 0x96, 0x0b, 0x95, 0x69, 0xfe, 0xd4, 0x51,
	0x36, 0x2f, 0x24, 0xbd, 0x84, 0xc3, 0x08, 0x9f, 0x44, 0x36, 0x96, 0xe1, 0xf6, 0x15, 0xcc, 0xdd,
	0x2b, 0xd4, 0xd6, 0xbe, 0x3f, 0xa4, 0x62, 0x63, 0x55, 0x19, 0xe7, 0x6e, 0xa9, 0x5e, 0x52, 0x0d,
	0xd7, 0xf2, 0x2c, 0x00, 0xd8, 0xf2, 0x1d, 0x41, 0x6d, 0x78, 0x3f, 0xe8, 0xb3, 0x8e, 0x7f, 0xe3,
	0xb3, 0x6e, 0x38, 0x08, 0xae, 0x02, 0xe6, 0x18, 0x14, 0xa0, 0xfc, 0x30, 0x64, 0x43, 0xd6, 0x75,
	0x08, 0x3d, 0x00, 0xab, 0xcb, 0x72, 0x15, 0xf6, 0xee, 0x1c, 0x93, 0x52, 0xa8, 0x6e, 0x00, 0xe3,
	0xbc, 0xc7, 0x9d, 0xd2, 0xb5, 0xfb, 0xb5, 0xf4, 0xc8, 0x62, 0xe9, 0x91, 0x9f, 0xa5, 0x47, 0x3e,
	0x57, 0x9e, 0xb1, 0x58, 0x79, 0xc6, 0xf7, 0xca, 0x33, 0x1e, 0xcb, 0xfa, 0x77, 0xdb, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x91, 0xca, 0x74, 0xea, 0xeb, 0x01, 0x00, 0x00,
}

func (m *ChannelPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChannelPayload) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.EventState != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintData(dAtA, i, uint64(m.EventState))
	}
	if m.RequeueCount != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintData(dAtA, i, uint64(m.RequeueCount))
	}
	return i, nil
}

func (m *EventTimePayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventTimePayload) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.CreateTime != 0 {
		dAtA[i] = 0x9
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(m.CreateTime))
		i += 8
	}
	return i, nil
}

func (m *IndexPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndexPayload) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.EventId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintData(dAtA, i, uint64(len(m.EventId)))
		i += copy(dAtA[i:], m.EventId)
	}
	if m.CreateTime != 0 {
		dAtA[i] = 0x11
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(m.CreateTime))
		i += 8
	}
	return i, nil
}

func (m *EventPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPayload) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Payload) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintData(dAtA, i, uint64(len(m.Payload)))
		i += copy(dAtA[i:], m.Payload)
	}
	if m.DefaultEventState != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintData(dAtA, i, uint64(m.DefaultEventState))
	}
	if len(m.Indexes) > 0 {
		for _, s := range m.Indexes {
			dAtA[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func encodeVarintData(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ChannelPayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EventState != 0 {
		n += 1 + sovData(uint64(m.EventState))
	}
	if m.RequeueCount != 0 {
		n += 1 + sovData(uint64(m.RequeueCount))
	}
	return n
}

func (m *EventTimePayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CreateTime != 0 {
		n += 9
	}
	return n
}

func (m *IndexPayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EventId)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	if m.CreateTime != 0 {
		n += 9
	}
	return n
}

func (m *EventPayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	if m.DefaultEventState != 0 {
		n += 1 + sovData(uint64(m.DefaultEventState))
	}
	if len(m.Indexes) > 0 {
		for _, s := range m.Indexes {
			l = len(s)
			n += 1 + l + sovData(uint64(l))
		}
	}
	return n
}

func sovData(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozData(x uint64) (n int) {
	return sovData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ChannelPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChannelPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChannelPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventState", wireType)
			}
			m.EventState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventState |= EventState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequeueCount", wireType)
			}
			m.RequeueCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequeueCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventTimePayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventTimePayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventTimePayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTime", wireType)
			}
			m.CreateTime = 0
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			m.CreateTime = int64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
		default:
			iNdEx = preIndex
			skippy, err := skipData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IndexPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndexPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndexPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTime", wireType)
			}
			m.CreateTime = 0
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			m.CreateTime = int64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
		default:
			iNdEx = preIndex
			skippy, err := skipData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultEventState", wireType)
			}
			m.DefaultEventState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultEventState |= EventState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Indexes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Indexes = append(m.Indexes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthData
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthData
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowData
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipData(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthData
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthData = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowData   = fmt.Errorf("proto: integer overflow")
)
