---
image:
  repository: registry.gitlab.com/katchecode/services/gcs-blob-svc/gcs-blob-svc
  tag: ''
  # pullSecret: docker-registry-auth
  pullPolicy: IfNotPresent

tests:
  image:
    repository: registry.gitlab.com/katchecode/services/gcs-blob-svc/gcs-blob-svc-tests
    tag: ''
    # pullSecret: docker-registry-auth
    pullPolicy: IfNotPresent
  resources: {}

gcs:
  bucket: assets.example.com
  prefix: ''
  # credentialsSecret:
  #   name: gcs-secret
  #   value: googleApplicationCredentials

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  replicas:
    min: 1
    max: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75

rollingUpdate: {}
  # maxUnavailable: 1

debug: false
develop: false

nodeSelector: {}

  # secret: jwt-ecdsa
  # item: privatekey

# bootstrapAdmin:
#   email: admin@example.com
#   password: PLEASE change this immediately
