apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: {{ template "fullname" . }}
  minReplicas: {{ .Values.autoscaling.replicas.min }}
  maxReplicas: {{ .Values.autoscaling.replicas.max }}
  metrics:
{{ toYaml .Values.autoscaling.metrics | indent 4 }}
