{{ if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{ if .Values.persistence.storageClass -}}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{ end -}}
{{- end }}
